### ISSUE TITLE
move versioning for logfiles to the left of the dot

### ISSUE THREAD

**Issue by pwil** [kalahari/DnsDirector#5]
DnsDirector.Service.log.txt.1
DnsDirector.Service.log.txt.2016-04-18
DnsDirector.Service.log.txt.2016-04-18.1

All of the above log file names result in unassociated filetypes.  Would much prefer keeping the .txt on the end and moving the versioning inside the dot, ie:
DnsDirector.Service.log.1.txt
DnsDirector.Service.log.2016-04-18.txt
DnsDirector.Service.log.2016-04-18.1.txt

**Comment by kalahari** [comment]
Looks like a simple fix to the log4net config file: http://stackoverflow.com/questions/13609089/how-to-append-rolling-index-before-file-extension-in-log-filename

**Comment by kalahari** [comment]
Confirmed
